radar:
  device: AWR1843
  port: null
  frequency: 77.0
  idle_time: 95.0
  adc_start_time: 5.7
  ramp_end_time: 59.0
  tx_start_time: 1.0
  freq_slope: 67.5
  adc_samples: 128
  sample_rate: 2500
  frame_length: 128
  frame_period: 100.0
capture:
  sys_ip: 192.168.33.30
  fpga_ip: 192.168.33.180
  socket_buffer: 6291456
